- hosts: all
  become: yes
  roles:
    - role: common
  tags: commoncheck

- hosts: webserver
  become: yes
  roles:
    - role: webserver
  tags: web

- hosts: all
  become: yes
  roles: 
    - role: useradd
  tags: useradd

- hosts: all
  become: yes
  roles:
    - role: stat
  tags: stat

- hosts: database
  become: yes
  roles:
    - role: database
  tags: db
