---
- name: install apache2
  apt:
   name: apache2
   state: present

- name: Index html ozellerstirmesi
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache2

- name: apache2 timeout degerini ekleme
  copy:
    content: "{{ apache2 }}"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache2

- name: apache2 configuration dosyasını download etme
  fetch:
    src: /var/www/html/index.html
    dest: /tmp/index.html
    flat: yes
